#baseURL = "https://imposterdev.com"
baseURL = "/"
languageCode = "en-us"
title = "IMPOSTERDEV"
theme = "cactus"

[params]
  colortheme = "dark" # dark, light, white, or classic
  description = "I am imposterdev, I know basically nothing, or do I?"
  showAllPostsOnHomePage = false
  postsOnHomePage = 5
  mainSectionTitle = "Posts"
  tocInline = true
  showAllPostsArchive = true # or false (default)
  
  showProjectsList = false
  #projectsUrl = "https://github.com/monkeyWzr"
# Main menu which appears below site header.
[[params.social]]
  name = "email"
  link = "leo@redpill-linpro.com" # no need for "mailto:" at the start

[[params.social]]
  name = "linkedin"
  link = "https://se.linkedin.com/in/leo-jordansson-4330a5155"

[[params.social]]
  name = "github"
  link = "https://github.com/Karljord"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3



